/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tugaspboyusufmaulana;

/**
 *
 * @author Lenovo-LOQ
 */
public class LandingPage_Transaksi extends javax.swing.JFrame {
    private int selectedRow = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LandingPage_Transaksi.class.getName());

    /**
     * Creates new form LandingPage_Transaksi
     */
    public LandingPage_Transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCetakStruk = new javax.swing.JButton();
        btnKonfirmasi = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Manajemen Transaksi");

        jLabel2.setText("Verifikasi Pembayaran dan Kelola Struk Transaksi");

        btnCetakStruk.setText("Cetak Struk");
        btnCetakStruk.addActionListener(this::btnCetakStrukActionPerformed);

        btnKonfirmasi.setText("Konfirmasi Pembayaran");
        btnKonfirmasi.addActionListener(this::btnKonfirmasiActionPerformed);

        btnHapus.setText("Hapus Riwayat");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnRefresh.setText("Refresh Data");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        btnKembali.setText("Logout");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Tanggal", "Total Harga", "Status Pembayaran", "Kondisi Barang"
            }
        ));
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKonfirmasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCetakStruk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKembali, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKonfirmasi)
                .addGap(12, 12, 12)
                .addComponent(btnCetakStruk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKembali)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
         selectedRow = tabelTransaksi.getSelectedRow();
    }//GEN-LAST:event_tabelTransaksiMouseClicked

    private void btnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiActionPerformed
         if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih transaksi yang ingin dikonfirmasi!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelTransaksi.getModel();
    String statusSaatIni = model.getValueAt(selectedRow, 3).toString();
    
    if (statusSaatIni.equals("Lunas")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Transaksi ini sudah lunas!", "Informasi", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Konfirmasi bahwa pembayaran telah diterima?", "Konfirmasi Pembayaran", javax.swing.JOptionPane.YES_NO_OPTION);
    if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
        model.setValueAt("Lunas", selectedRow, 3);
        javax.swing.JOptionPane.showMessageDialog(this, "Pembayaran berhasil dikonfirmasi!\n(Status diubah menjadi Lunas).", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        tabelTransaksi.clearSelection();
        selectedRow = -1;
    }

    }//GEN-LAST:event_btnKonfirmasiActionPerformed

    private void btnCetakStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakStrukActionPerformed
          if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih transaksi untuk mencetak struk!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelTransaksi.getModel();
    String statusSaatIni = model.getValueAt(selectedRow, 3).toString();
    
    if (!statusSaatIni.equals("Lunas")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Struk hanya bisa dicetak untuk transaksi yang sudah Lunas!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    String idTrx = model.getValueAt(selectedRow, 0).toString();
    String tanggal = model.getValueAt(selectedRow, 1).toString();
    String total = model.getValueAt(selectedRow, 2).toString();
    String kondisi = model.getValueAt(selectedRow, 4).toString();

    String struk = """
                             STRUK TRANSAKSI           
                   ID Transaksi : """ + idTrx + "\n"
                 + "Tanggal      : " + tanggal + "\n"
                 + "Kondisi      : " + kondisi + "\n"
                 + "Status       : " + statusSaatIni + "\n"
                 + "------------------------------------\n"
                 + "TOTAL BAYAR  : Rp " + total + "\n"
                 + "====================================\n"
                 + "     Terima Kasih Atas Titipannya   \n"
                 + "====================================";

    javax.swing.JTextArea textArea = new javax.swing.JTextArea(struk);
    textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
    textArea.setEditable(false);
    javax.swing.JOptionPane.showMessageDialog(this, new javax.swing.JScrollPane(textArea), "Cetak Struk", javax.swing.JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_btnCetakStrukActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
         if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih transaksi yang ingin dihapus!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }
    int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus riwayat transaksi ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
    if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelTransaksi.getModel();
        model.removeRow(selectedRow);
        javax.swing.JOptionPane.showMessageDialog(this, "Riwayat transaksi dihapus!");
        selectedRow = -1;
        tabelTransaksi.clearSelection();
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
         tabelTransaksi.clearSelection();
    selectedRow = -1;
    javax.swing.JOptionPane.showMessageDialog(this, "Data Transaksi disinkronisasi ulang.");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
         int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin keluar?", "Logout", javax.swing.JOptionPane.YES_NO_OPTION);
    if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
        LOGIN_PAGE loginPage = new LOGIN_PAGE();
        loginPage.setVisible(true);

        // Baris di bawah ini adalah cara paling kuat (bulletproof) untuk menghindari error "dispose".
        // Ia akan mencari Jendela (Window/Frame) yang membungkus komponen ini, lalu menutupnya.
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor((java.awt.Component) evt.getSource());
        if (win != null) {
            win.dispose();
        }
    }
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LandingPage_Transaksi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetakStruk;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelTransaksi;
    // End of variables declaration//GEN-END:variables
}
