/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tugaspboyusufmaulana.TUBES;

/**
 *
 * @author Lenovo-LOQ
 */
public class LandingPage_Pembeli extends javax.swing.JFrame {
    private int selectedRow = -1;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LandingPage_Pembeli.class.getName());

    /**
     * Creates new form LandingPage_Pembeli
     */
    public LandingPage_Pembeli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKatalog = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnBeli = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Katalog Barang Bekas");

        tabelKatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Barang", "Nama Barang", "Kondisi", "Harga"
            }
        ));
        tabelKatalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKatalogMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKatalog);

        jLabel2.setText("Pilih barang yang ingin Anda beli");

        btnBeli.setText("Beli Barang");
        btnBeli.addActionListener(this::btnBeliActionPerformed);

        btnRefresh.setText("Refresh Katalog");
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnBeli)
                        .addGap(47, 47, 47)
                        .addComponent(btnRefresh)
                        .addGap(55, 55, 55)
                        .addComponent(btnLogout)))
                .addContainerGap(339, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBeli)
                    .addComponent(btnRefresh)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeliActionPerformed
         if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih barang dari katalog terlebih dahulu!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    String idBarang = tabelKatalog.getValueAt(selectedRow, 0).toString();
    String namaBarang = tabelKatalog.getValueAt(selectedRow, 1).toString();
    String hargaBarang = tabelKatalog.getValueAt(selectedRow, 3).toString();

    // Simulasi pop-up konfirmasi pembayaran
    int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, 
        "Anda akan membeli:\n" + namaBarang + "\nHarga: Rp " + hargaBarang + "\n\nLanjutkan ke pembayaran?", 
        "Konfirmasi Pembelian", 
        javax.swing.JOptionPane.YES_NO_OPTION);

    if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
        // Nanti di sini kamu bisa memanggil class/halaman Form_Pembayaran atau Transaksi
        // Untuk sekarang, kita tampilkan pesan sukses
        javax.swing.JOptionPane.showMessageDialog(this, "Pembayaran berhasil! Transaksi untuk " + namaBarang + " sedang diproses.", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // Opsional: Hapus baris dari tabel karena sudah dibeli (simulasi)
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tabelKatalog.getModel();
        model.removeRow(selectedRow);
        selectedRow = -1;
    }

    }//GEN-LAST:event_btnBeliActionPerformed

    private void tabelKatalogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKatalogMouseClicked
          selectedRow = tabelKatalog.getSelectedRow();
    }//GEN-LAST:event_tabelKatalogMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
            tabelKatalog.clearSelection();
    selectedRow = -1;
    javax.swing.JOptionPane.showMessageDialog(this, "Katalog diperbarui.");
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
            int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin keluar?", "Logout", javax.swing.JOptionPane.YES_NO_OPTION);
    if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
        LOGIN_PAGE loginPage = new LOGIN_PAGE();
        loginPage.setVisible(true);
        
        // Menutup frame secara aman
        java.awt.Window win = javax.swing.SwingUtilities.getWindowAncestor((java.awt.Component) evt.getSource());
        if (win != null) {
            win.dispose();
        }
    }

    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LandingPage_Pembeli().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeli;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKatalog;
    // End of variables declaration//GEN-END:variables
}
